@url = http://localhost:3030




# ----
# AUTH
# ----

### SignUp
POST {{url}}/v1/signup
Content-Type: application/json

{
  "email" : "student@university.id",
  "password" : "123",
}

### Login
POST {{url}}/v1/login
Content-Type: application/json

{
  "email" : "student@university.id",
  "password" : "123",
}




# -------
# STUDENT
# -------

### GetAll Student 
GET {{url}}/v1/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTczMzk5OTAsInN1YiI6MX0.EZO8aoijEd51h91B31G7v1KG-q-iu1ym680vvmA6HxI

### GetByID Student
GET {{url}}/v1/students/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTczMzk5OTAsInN1YiI6MX0.EZO8aoijEd51h91B31G7v1KG-q-iu1ym680vvmA6HxI

### Post
POST {{url}}/v1/students
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTczMzk5OTAsInN1YiI6MX0.EZO8aoijEd51h91B31G7v1KG-q-iu1ym680vvmA6HxI

{
  "name" : "Student One",
  "address" : "Tangerang",
  "major" : "Informatics Engineering",
  "phone" : "0317938748",
  "email" : "studentone@ie.com",
  "birthdate" : "2000-01-10"
}

### Put
PUT {{url}}/v1/students/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTczMzk5OTAsInN1YiI6MX0.EZO8aoijEd51h91B31G7v1KG-q-iu1ym680vvmA6HxI

{
  "name" : "Student One",
  "address" : "Jakarta",
  "major" : "Informatics Engineering",
  "phone" : "0317938748",
  "email" : "studentone@ie.com",
  "birthdate" : "2003-01-10"
}

### Delete
DELETE  {{url}}/v1/students/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTczMzk5OTAsInN1YiI6MX0.EZO8aoijEd51h91B31G7v1KG-q-iu1ym680vvmA6HxI




# -------
# COURSES
# -------

### GetAll Courses 
GET {{url}}/v1/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTczMzk5OTAsInN1YiI6MX0.EZO8aoijEd51h91B31G7v1KG-q-iu1ym680vvmA6HxI

### GetByID Courses
GET {{url}}/v1/courses/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTczMzk5OTAsInN1YiI6MX0.EZO8aoijEd51h91B31G7v1KG-q-iu1ym680vvmA6HxI

### Add Courses to Student
GET {{url}}/v1/students/add-course?studentID=1&courseID=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTczMzk5OTAsInN1YiI6MX0.EZO8aoijEd51h91B31G7v1KG-q-iu1ym680vvmA6HxI

### Post
POST {{url}}/v1/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTczMzk5OTAsInN1YiI6MX0.EZO8aoijEd51h91B31G7v1KG-q-iu1ym680vvmA6HxI

{
  "name" : "Pemrograman Dasar"
}

### Put
PUT {{url}}/v1/courses/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTczMzk5OTAsInN1YiI6MX0.EZO8aoijEd51h91B31G7v1KG-q-iu1ym680vvmA6HxI

{
  "name" : "Pemrograman Berorientasi Objek"
}

### Delete
DELETE  {{url}}/v1/courses/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTczMzk5OTAsInN1YiI6MX0.EZO8aoijEd51h91B31G7v1KG-q-iu1ym680vvmA6HxI