@url = http://localhost:3030

### GetAll Student 
GET {{url}}/v1/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTcyNjY4MDQsInN1YiI6MX0.wBq_znZZTkdhEAkzmtOq71723Qq6Kyoob0PWnDruU6Q

### GetByID Student
GET {{url}}/v1/students/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTcyNjY4MDQsInN1YiI6MX0.wBq_znZZTkdhEAkzmtOq71723Qq6Kyoob0PWnDruU6Q

### GetAll Courses 
GET {{url}}/v1/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTcyNjY4MDQsInN1YiI6MX0.wBq_znZZTkdhEAkzmtOq71723Qq6Kyoob0PWnDruU6Q

### GetByID Student
GET {{url}}/v1/students/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTcyNjY4MDQsInN1YiI6MX0.wBq_znZZTkdhEAkzmtOq71723Qq6Kyoob0PWnDruU6Q

### SignUp
POST {{url}}/v1/signup
Content-Type: application/json

{
  "email" : "student@university.id",
  "password" : "123",
}

### Login
POST {{url}}/v1/login
Content-Type: application/json

{
  "email" : "student@university.id",
  "password" : "123",
}

### Post
POST {{url}}/v1/students
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTcxODcwMjcsInN1YiI6MX0.8eBMTufHrZuspM04YwiCfcl11HnSPqhVmDii9NlV94M

{
  "name" : "Student Two",
  "address" : "Tangerang",
  "major" : "Informatics Engineering",
  "phone" : "0317938748",
  "email" : "student2@gmail.com",
  "birthdate" : "2000-01-01"
}

### Put
PUT {{url}}/v1/students/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTcyNjY4MDQsInN1YiI6MX0.wBq_znZZTkdhEAkzmtOq71723Qq6Kyoob0PWnDruU6Q

{
  "name" : "Student Two",
  "address" : "Tangerang",
  "major" : "Informatics Engineering",
  "phone" : "0317938748",
  "email" : "student2@gmail.com",
  "birthdate" : "2000-01-01"
}

### Delete
DELETE  {{url}}/v1/students/2